from __future__ import annotations

from recon.domain.graph.relation import RelationRule


RELATION_RULES = (
    RelationRule(
        source_type="merchant_order",
        target_type="razorpay_order",
        edge_type="REFERENCES_RAZORPAY_ORDER",
        source_field="razorpay_order_id",
        target_field="order_id",
    ),
    RelationRule(
        source_type="merchant_order",
        target_type="ledger_entry",
        edge_type="HAS_LEDGER_ENTRY",
        source_field="merchant_order_id",
        target_field="merchant_order_id",
    ),
    RelationRule(
        source_type="merchant_order",
        target_type="pos_transaction",
        edge_type="HAS_POS_TRANSACTION",
        source_field="merchant_order_id",
        target_field="merchant_order_id",
    ),
    RelationRule(
        source_type="merchant_order",
        target_type="gateway_transaction",
        edge_type="HAS_GATEWAY_TRANSACTION",
        source_field="merchant_order_id",
        target_field="merchant_order_id",
    ),
    RelationRule(
        source_type="razorpay_order",
        target_type="payment",
        edge_type="HAS_PAYMENT",
        source_field="order_id",
        target_field="order_id",
    ),
    RelationRule(
        source_type="payment",
        target_type="refund",
        edge_type="HAS_REFUND",
        source_field="payment_id",
        target_field="payment_id",
    ),
    RelationRule(
        source_type="payment",
        target_type="transfer",
        edge_type="HAS_TRANSFER",
        source_field="payment_id",
        target_field="payment_id",
    ),
    RelationRule(
        source_type="settlement",
        target_type="settlement_entry",
        edge_type="HAS_SETTLEMENT_ENTRY",
        source_field="settlement_id",
        target_field="settlement_id",
    ),
    RelationRule(
        source_type="settlement_entry",
        target_type="payment",
        edge_type="SETTLES_PAYMENT",
        source_field="payment_id",
        target_field="payment_id",
    ),
    RelationRule(
        source_type="settlement_entry",
        target_type="refund",
        edge_type="SETTLES_REFUND",
        source_field="refund_id",
        target_field="refund_id",
    ),
    RelationRule(
        source_type="settlement_entry",
        target_type="transfer",
        edge_type="SETTLES_TRANSFER",
        source_field="transfer_id",
        target_field="transfer_id",
    ),
    RelationRule(
        source_type="settlement_entry",
        target_type="adjustment",
        edge_type="SETTLES_ADJUSTMENT",
        source_field="adjustment_id",
        target_field="adjustment_id",
    ),
    RelationRule(
        source_type="settlement",
        target_type="bank_transaction",
        edge_type="MATCHES_BANK_UTR",
        source_field="utr",
        target_field="utr",
    ),
)